english_to_chinese = {
    "company_name": "公司名称",
    "credit_number": "社会信用代码",
    "province": "省份",
    "company_type": "公司类型",
    "city": "市",
    "district_info": "区县信息",
    "main_business": "主营业务",
    "a_stock_code": "A股证券代码",
    "organization_form": "组织形式",
    "security_name": "证券名称",
    "stock_abbreviation": "股票简称",
    "security_code": "证券代码",
    "board_secretary_code": "董事会秘书代码",
    "business_scope": "经营范围",
    "registered_address": "注册地址",
    "legal_representative": "法定代表人",
    "former_company_name": "公司曾用名",
    "company_phone": "公司电话",
    "company_profile": "公司简介",
    "english_name": "英文名称",
    "b_stock_code": "B股证券代码",
    "actual_controller": "实际控制人"
}

chinese_to_english = {
    "公司名称": "company_name",
    "社会信用代码": "credit_number",
    "省份": "province",
    "公司类型": "company_type",
    "市": "city",
    "区县信息": "district_info",
    "主营业务": "main_business",
    "A股证券代码": "a_stock_code",
    "组织形式": "organization_form",
    "证券名称": "security_name",
    "股票简称": "stock_abbreviation",
    "证券代码": "security_code",
    "董事会秘书代码": "board_secretary_code",
    "经营范围": "business_scope",
    "注册地址": "registered_address",
    "法定代表人": "legal_representative",
    "公司曾用名": "former_company_name",
    "公司电话": "company_phone",
    "公司简介": "company_profile",
    "英文名称": "english_name",
    "B股证券代码": "b_stock_code",
    "实际控制人": "actual_controller"
}
